export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_PSEUDONYM = 'SET_PSEUDONYM';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_JWT_TOKEN = 'SET_JWT_TOKEN'
export const HANDLE_RATING_CHANGE = 'HANDLE_RATING_CHANGE';
export const CLEAR_RATING_CHANGES = "CLEAR_RATING_CHANGES";